### PR TITLE
Remove light styles link instead of adding media query

### PR DESCRIPTION
**Pull request by BackThePortal**
When the light theme is set on page load, the switch theme button doesn't work correctly.

Removing and adding the `<link>` element containing the light styles instead of using the `media="not all"` attribute fixes this issue.

### CODE REVIEW

**Comment by GrahamSH-LLK** [comment]
This doesn't make much sense to me, but I'm going to be back to my computer tommorrow and I'll try to find the root cause (I don't think the media not all is all that's going on here)

**Comment by BackThePortal** [comment]
Taking into account how vue 3 handles styles differently, in my opinion it's better to add/remove the link tag rather than using the media attribute. It makes more sense to me doing the former and it seems to have solved the issue.

Although maybe you're right, gonna check with the media attribute.

**Comment by BackThePortal** [comment]
Tried it with an old commit in this branch, before I began contributing, and the problem is there. I didn't really try to find the cause, I just thought that doing it this way would avoid weird style bugs.

**Comment by GrahamSH-LLK** [comment]
i'm pretty sure i just patched this. your code was inserting the light tag twice so it never got disabled

**Pull request closed without merging**
